repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: local
    hooks:
      - id: run-command-command_server-tests
        name: Run Command Server tests
        entry: >
          bash -c 'cd command_server python manage.py test'
        language: system
        types: [ python ]
        always_run: true

  - repo: local
    hooks:
      - id: run-command-query_server-tests
        name: Run Query Server tests
        entry: >
          bash -c 'cd query_server python manage.py test'
        language: system
        types: [ python ]
        always_run: true
