version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ server
      - "15672:15672"  # RabbitMQ management plugin
    networks:
      - backend

networks:
  backend:
    driver: bridge
